### ISSUE TITLE
Call to fastme via subprocess.call should be passed as sequence instead of string

### ISSUE THREAD

**Issue by pierrebarbera** [balabanmetin/apples#1]
Calling the program fails for me as `subprocess.call` tries to interpret the full string specified here:

https://github.com/balabanmetin/apples/blob/master/apples.py#L349

as the path to an executable. To increase platform independence (and avoid the crash I experienced) I suggest switching to specifying the executable path and individual args as a list:

```python
s = [fastme_exec, "-c", "-{}J".format(datatype), "-i", aln_fp, "-O", dist_fp, "-Q", placement_set_size]
subprocess.call(s, stdout = nldef, stderr = nldef)
```

See also this SO thread: https://stackoverflow.com/questions/15109665/subprocess-call-using-string-vs-using-list/15109975#15109975

**Comment by balabanmetin** [comment]
Changes are applied.
