### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes 

### ISSUE THREAD

**Issue by dgslos** [balabanmetin/apples#7]
![image](https://user-images.githubusercontent.com/65173064/84478779-24279d00-ac92-11ea-9154-339d1a9367b1.png)

**Comment by balabanmetin** [comment]
query alignment BC1_aligned.fa contains one sequence with length 6993 and while reference alignment contains one with length 1121. make sure that every sequence in reference and query alignments are the same length.

**Comment by dgslos** [comment]
Aha, that's the reason, the error was hard to read. Thanks for the information!
